listen_addresses = ['127.0.0.1:53']
max_clients = 250
ipv4_servers = true
ipv6_servers = false
dnscrypt_servers = true
doh_servers = false
require_dnssec = false
require_nolog = true
require_nofilter = false
force_tcp = false
timeout = 2500
cert_refresh_delay = 240
fallback_resolvers = ['84.200.69.80:53', '212.129.46.32:53']
ignore_system_dns = false
block_ipv6 = true
cache = true
cache_size = 256
cache_min_ttl = 600
cache_max_ttl = 86400
cache_neg_ttl = 60
[sources]
[sources.'cs-resolvers']
urls = ['https://cryptostorm.is/cs-resolvers.md', 'https://raw.githubusercontent.com/cryptostorm/cstorm_deepDNS/master/cs-resolvers.md']
cache_file = 'cs-resolvers.md'
minisign_key = 'RWTzXTWKLLKfM3fRQW0CUwSN17U3YMsVcVdfi3ERraxuttv2tL8dsdUE'
refresh_delay = 72
[sources.'cs-relays']
urls = ['https://cryptostorm.is/cs-relays.md', 'https://raw.githubusercontent.com/cryptostorm/cstorm_deepDNS/master/cs-relays.md']
cache_file = 'cs-relays.md'
minisign_key = 'RWTzXTWKLLKfM3fRQW0CUwSN17U3YMsVcVdfi3ERraxuttv2tL8dsdUE'
prefix = ''
